### ISSUE TITLE
How i can use API Pal Gate?

### ISSUE THREAD

**Issue by damire-da** [RoeiOfri/homebridge-palgate-opener#18]
**Problem:** We have the Pal Gate app installed on our phone. We have a parking lot. There are automatic gates in the parking lot. To open them, the user sends a call to the number. This call is somehow intercepted by Pal Gate and captures a record of whether the user has entered or left.
So, I need data to analyze who left or drove in. Is there a Pal Gate API? (I didn't find it). But I came across this repository. Will it help me?
Thanks in advance for the answers.

**Comment by andybenichou** [comment]
I have tried to reversed engineering also to get the token from the networks calls when using the desktop app. But it wasn't working.

Do you have some way to get the authentification token?

Thanks

**Comment by RedFraction** [comment]
Any UPDs?

**Comment by RoeiOfri** [comment]
Updates on what? This issue is closed, please check the readme file in the repo, all was fixed a while back.
