### ISSUE TITLE
"Characteristic is not defined" Error persist

### ISSUE THREAD

**Issue by nitaybz** [RoeiOfri/homebridge-palgate-opener#6]
Seeing this issue on version 1.0.5

`[24/02/2021, 21:30:35] [homebridge-palgate-opener] This plugin threw an error from the characteristic 'Target Door State': Unhandled error thrown inside write handler for characteristic: Characteristic is not defined. See https://git.io/JtMGR for more info.`

**Comment by RoeiOfri** [comment]
Resolved by @nitaybz fix. Thanks!

**Comment by RoeiOfri** [comment]
I’ll publish a new version later on..
