### ISSUE TITLE
Failed to load schema

### ISSUE THREAD

**Issue by gamlielalon1983** [RoeiOfri/homebridge-palgate-opener#9]
Hi
You closed the previous issue just to let you know also two of my colleagues installed the plugin and got the same error.

Will be great if you can check it.

Not going to interfere you more 
Thanks

**Comment by RoeiOfri** [comment]
Thanks for reaching out again, I see no issue thus the previous issue was closed. But just to be sure I will try to reproduce it on my environment later on and I’ll keep you posted.
Please stay tuned.

**Comment by aml11** [comment]
@gamlielalon1983 did you guys just try and use an older version? say 1.0.5?

**Comment by gamlielalon1983** [comment]
I tried  same issue.
I uninstall the latest one and installed the previous one same
error message.

**Comment by RoeiOfri** [comment]
Hi, Following your issue, configuring the plugin wasn't supported hence you got the error "Failed to load schema file".
I've fixed the issue in v1.0.7 which was just published.
Please update and try again and update me for any issues by opening a new issue.

Thanks for your attention to the issue.

**Comment by RoeiOfri** [comment]
Correction: Please upgrade to v1.0.8.
